### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by rokibot009** [OguzhanUmutlu/ComplexPets#12]
My server has crash Idk why..? Can u fix it?

Last i riding a ghast and baby wolf and got crashed

Sry i have a bad english

<header class="header" style="padding: 0px; margin: 0px; font-family: Play, sans-serif; box-sizing: border-box; height: 60px; width: 384px; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; background-color: rgb(45, 57, 67); display: flex; align-items: center; color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://aternos.org/:id/" class="logo" style="padding: 0px 5px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; height: 48px; display: flex; align-items: center; justify-content: center; max-height: 36px; flex-grow: 1; text-align: center;"><br class="Apple-interchange-newline"><img src="https://aternos.org/panel/img/logo-white.svg" alt="Aternos Logo" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; max-height: 100%; width: auto; max-width: 100%; height: 36px;"></a><div class="help" style="padding: 0px; margin: 0px 0px 0px 4px; font-family: var(--font-main); box-sizing: border-box;"><div class="btn btn-main btn-notext-mobile" onclick="openSupport()" style="padding: 8px 10px; margin: 10px 8px 10px 0px; font-family: var(--font-main); box-sizing: border-box; border-radius: 2px; font-weight: var(--bold,700); font-size: 18px; display: inline-block; transition: background 0.05s ease 0s; cursor: pointer; white-space: nowrap; background-color: var(--color-main); color: var(--color-light,#f0f0f0);"><i class="fas fa-question-circle" style="padding: 0px; margin: 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1;"></i></div></div><div class="user" style="padding: 0px 12px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: var(--color-light); display: flex; height: 60px; align-items: center; position: relative; border-left: none;"><div class="usericon" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; position: relative;"><a href="https://aternos.org/account/" id="userdropdown-toggle" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none;"><i class="fas fa-ellipsis-h mobile-icon" style="padding: 0px; margin: 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 32px; vertical-align: middle;"></i></a></div></div></header><div class="body" id="read-our-tos" style="padding: 0px; margin: 0px; font-family: Play, sans-serif; box-sizing: border-box; height: calc(100% - 60px); display: flex; position: relative; color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><nav class="navigation" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; height: 619.467px; overflow-y: auto; width: 200px; min-width: 200px; flex-basis: 200px; background: var(--color-dark); color: var(--color-light); z-index: 10; display: flex; flex-direction: column; position: absolute; top: 0px; left: -200px;"><div class="navigation-server offline" style="padding: 8px 12px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; display: flex; align-items: center; justify-content: center; width: 200px; background-image: linear-gradient(rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1)); border-left-width: ; border-left-style: ; border-color: var(--color-danger);"><div class="navigation-server-info" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; max-width: calc(100% - 60px);"><div class="navigation-server-name" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; font-weight: var(--bold); font-size: 14px; max-width: 100%; text-overflow: ellipsis; overflow: hidden; white-space: nowrap; min-width: 1px;">SurvivalGabuds</div><div class="navigation-server-detail navigation-server-id" style="padding: 0px; margin: 0px 0px 4px; font-family: var(--font-main); box-sizing: border-box; font-size: 8px; max-width: 100%; text-overflow: ellipsis; overflow: hidden; white-space: nowrap; min-width: 1px; color: rgb(164, 164, 164);">#e5TXddCdBGUFxNKe</div></div><div class="navigation-server-icon statusicon" style="padding: 0px; margin: 0px 0px 0px auto; font-family: var(--font-main); box-sizing: border-box; font-size: 18px; max-width: 60px; color: var(--color-danger);"><i class="fas fa-heart-broken" style="padding: 0px; margin: 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1;"></i></div></div><a href="https://aternos.org/server/" class="item" title="Peladen" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-power-off" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Peladen</span></a><a href="https://aternos.org/options/" class="item" title="Pengaturan" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-sliders-h-square" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Pengaturan</span></a><a href="https://aternos.org/console/" class="item" title="Konsol" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-terminal" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Konsol</span></a><a href="https://aternos.org/log/" class="item active" title="Log" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-file-alt" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Log</span></a><a href="https://aternos.org/players/" class="item" title="Pemain" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-users" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Pemain</span></a><a href="https://aternos.org/software/" class="item" title="Perangkat lunak" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-cogs" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Perangkat lunak</span></a><a href="https://aternos.org/addons/" class="item" title="Plugins" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-puzzle-piece" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Plugins</span></a><a href="https://aternos.org/files/" class="item" title="Berkas" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-folders" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Berkas</span></a><a href="https://aternos.org/worlds/" class="item" title="World" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-globe-americas" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">World</span></a><a href="https://aternos.org/backups/" class="item" title="Backup" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-history" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">Backup<span> </span><i class="fas fa-exclamation-triangle backup-warn-icon" style="padding: 0px; margin: 0px 8px 0px 5px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 16px; width: 24px; text-align: left; color: var(--color-warn);"></i></span></a><a href="https://aternos.org/access/" class="item" title="akses" style="padding: 8px 6px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; color: inherit; text-decoration: none; display: flex; position: relative; font-size: 14px; cursor: pointer; align-items: center; border-left: 5px solid transparent;"><i class="fas fa-user-lock" style="padding: 0px; margin: 0px 8px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1; font-size: 18px; width: 24px; text-align: center;"></i><span class="navigation-item-label" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;">akses</span></a><div class="navigation-settings" style="padding: 0px; margin: auto 0px 0px; font-family: var(--font-main); box-sizing: border-box; width: 200px; min-height: 53px; display: flex; align-items: center;"><div class="navigation-darkmode-toggle js-darkmode-toggle" style="padding: 16px 24px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; font-size: 18px; cursor: pointer;"><i class="fas fa-sun" style="padding: 0px; margin: 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 900; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1;"></i></div><div class="navigation-toggle" style="padding: 8px 20px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; flex-grow: 1; font-size: 28px; cursor: pointer; text-align: right; max-width: 100%;"><i class="far fa-angle-double-left" style="padding: 0px; margin: 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 400; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1;"></i></div></div></nav><main class="main" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; height: 619.467px; color: var(--color-dark); position: relative; display: flex; flex-grow: 1; z-index: 0; background: var(--color-light);"><section class="content" style="padding: 20px 15px 10px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; flex-grow: 1; height: 619.467px; overflow: hidden auto; width: 0px; position: relative; display: flex; flex-direction: column; justify-content: space-between; max-width: 100vw;"><div class="ad responsive-leaderboard mobile-full-width ad-dfp ad-detect" style="padding: 0px; margin: 8px -15px; font-family: var(--font-main); box-sizing: border-box; width: auto; flex-shrink: 0; overflow: hidden; border-radius: 0px;"><div class="ad-label-wrapper" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; display: flex; justify-content: center;"><div class="ad-label" style="padding: 0px; margin: 0px 0px 2px; font-family: var(--font-main); box-sizing: border-box; color: rgb(171, 171, 171); font-size: 12px;">Iklan</div></div></div><div id="global-message-container" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box;"></div><div class="page-content page-log" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; flex-grow: 1; max-width: 100vw;"><div class="log-title" style="padding: 0px; margin: 0px 0px 8px; font-family: var(--font-main); box-sizing: border-box; display: flex; flex-wrap: wrap; align-items: center;"><h1 style="padding: 0px; margin: 0px auto 0px 0px; font-family: var(--font-main); box-sizing: border-box; font-size: 24px; color: var(--color-main); font-weight: var(--bold);">Log</h1><div class="share-container" style="padding: 0px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; position: relative;"><div class="mclogs-share btn btn-main btn-large btn-no-margin" style="padding: 8px 12px 8px 10px; margin: 0px; font-family: var(--font-main); box-sizing: border-box; border-radius: 2px; font-weight: var(--bold,700); font-size: 16px; display: inline-block; transition: background 0.05s ease 0s; cursor: pointer; white-space: nowrap; background-color: var(--color-main); color: var(--color-light,#f0f0f0);"><i class="far fa-share-square" style="padding: 0px; margin: 0px 5px 0px 0px; font-family: &quot;Font Awesome 5 Pro&quot;; box-sizing: border-box; font-weight: 400; -webkit-font-smoothing: antialiased; display: inline-block; font-style: normal; font-variant: normal; text-rendering: auto; line-height: 1;"></i><span> </span>Bagikan</div></div></div><div class="log mobile-full-width" style="padding: 12px; margin: 8px -15px; font-family: var(--font-mono); box-sizing: border-box; background: var(--color-dark); color: var(--color-light); font-variant-ligatures: none; border-radius: 0px; word-break: break-all; width: auto; font-size: 12px; overflow-y: scroll;">

  | 2021-08-05 [20:10:50] [Server thread/INFO]: Loading pocketmine.yml...
-- | --
  | 2021-08-05 [20:10:50] [Server thread/INFO]: Loading server properties...
  | 2021-08-05 [20:10:50] [Server thread/INFO]: Selected English (eng) as the base language
  | 2021-08-05 [20:10:50] [Server thread/INFO]: Starting Minecraft: Bedrock Edition server version v1.17.10
  | 2021-08-05 [20:10:50] [Server thread/INFO]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
  | 2021-08-05 [20:10:50] [Server thread/INFO]: Opening server on 0.0.0.0:56667
  | 2021-08-05 [20:10:50] [Server thread/INFO]: This server is running PocketMine-MP version 3.22.0
  | 2021-08-05 [20:10:50] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Loading resource packs...
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Loading ComplexPets v1.0.0
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Loading AutoClearLagg v3.1.0
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Loading PureEntitiesX v0.7.0
  | 2021-08-05 [20:10:52] [Server thread/INFO]: [PureEntitiesX] Originally written by milk0417. Currently maintained by RevivalPMMP for PMMP 'REDACTED'.
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Enabling PureEntitiesX v0.7.0
  | 2021-08-05 [20:10:52] [Server thread/NOTICE]: [PureEntitiesX] Configuration loaded: [enableNBT:1] [enableSpawn:1] [enableAsyncTasks:1] [enableLookingTasks:1]] [findPartnerDistance:49] [interactDistance:3] [teleportTamedDistance:20] [tamedFollowDistance:14] [blockOfInterestTicks:100] [checkTargetSkipTicks:5] [pickupLootTicks:10] [interactiveButtonCorrection:1] [useBlockLight:] [useSkyLight:] [emitLoveParticles:1] [xpEnabled:] [idleChance:80] [idleMin:100] [idleMax:500] [idleTimeBetween:20secs] [panicEnabled:1] [panicTicks:100] [entityMaxAge:72000]
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Preparing world "world"
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Enabling ComplexPets v1.0.0
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Enabling AutoClearLagg v3.1.0
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Starting GS4 status listener
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Setting query port to 56667
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Query running on 0.0.0.0:56667
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Default game type: Survival Mode
  | 2021-08-05 [20:10:52] [Server thread/INFO]: If you find this project useful, please consider donating to support development: https://patreon.com/pocketminemp
  | 2021-08-05 [20:10:52] [Server thread/INFO]: Done (2.029s)! For help, type "help" or "?"
  | 2021-08-05 [20:10:52] [Server thread/WARNING]: ----- PocketMine-MP Auto Updater -----
  | 2021-08-05 [20:10:52] [Server thread/WARNING]: Your version of PocketMine-MP is out of date. Version 3.22.1 was released on Fri Jul 23 07:04:20 2021
  | 2021-08-05 [20:10:52] [Server thread/WARNING]: Details: https://jenkins.pmmp.io/job/PocketMine-MP/1844/
  | 2021-08-05 [20:10:52] [Server thread/WARNING]: Download: https://jenkins.pmmp.io/job/PocketMine-MP/1844//artifact/PocketMine-MP.phar
  | 2021-08-05 [20:10:52] [Server thread/WARNING]: ----- -------------------------- -----
  | 2021-08-05 [20:12:26] [Server thread/INFO]: rokibot009[] logged in with entity id 2 at (world, 315.9359, 66.052, 287.6618)
  | 2021-08-05 [20:12:42] [Server thread/INFO]: rokibot009 joined the game
  | 2021-08-05 [20:14:51] [Server thread/INFO]: Entities will clear in 60 seconds
  | 2021-08-05 [20:15:21] [Server thread/INFO]: Entities will clear in 30 seconds
  | 2021-08-05 [20:15:36] [Server thread/INFO]: Entities will clear in 15 seconds
  | 2021-08-05 [20:15:41] [Server thread/INFO]: Entities will clear in 10 seconds
  | 2021-08-05 [20:15:46] [Server thread/INFO]: Entities will clear in 5 seconds
  | 2021-08-05 [20:15:47] [Server thread/INFO]: Entities will clear in 4 seconds
  | 2021-08-05 [20:15:48] [Server thread/INFO]: Entities will clear in 3 seconds
  | 2021-08-05 [20:15:49] [Server thread/INFO]: Entities will clear in 2 seconds
  | 2021-08-05 [20:15:50] [Server thread/INFO]: Entities will clear in 1 seconds
  | 2021-08-05 [20:15:51] [Server thread/INFO]: Cleared a total of 3 entities
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: RuntimeException: "Tag with name "petOwner" not found and no valid default value given" (EXCEPTION) in "pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag" at line 176
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #0 pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag(215): pocketmine\nbt\tag\CompoundTag->getTagValue(string[8] petOwner, string[28] pocketmine\nbt\tag\StringTag, NULL , boolean )
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #1 plugins/ComplexPets.phar/src/OguzhanUmutlu/ComplexPets/entities/PetEntity(136): pocketmine\nbt\tag\CompoundTag->getString(string[8] petOwner)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #2 plugins/ComplexPets.phar/src/OguzhanUmutlu/ComplexPets/entities/types/DogPet(11): OguzhanUmutlu\ComplexPets\entities\PetEntity->initEntity()
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/entity/Entity(638): OguzhanUmutlu\ComplexPets\entities\types\DogPet->initEntity()
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #4 pmsrc/src/pocketmine/entity/Entity(381): pocketmine\entity\Entity->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #5 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/PureEntities(235): pocketmine\entity\Entity::createEntity(integer 14, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #6 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/PureEntities(254): revivalpmmp\pureentities\PureEntities::create(integer 14, object pocketmine\level\Position)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #7 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(230): revivalpmmp\pureentities\PureEntities->scheduleCreatureSpawn(object pocketmine\level\Position, integer 14, object pocketmine\level\Level, string[7] hostile, boolean )
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #8 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(291): revivalpmmp\pureentities\task\AutoSpawnTask->spawnPackToLevel(object pocketmine\math\Vector3, integer 14, object pocketmine\level\Level, string[7] hostile)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #9 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(117): revivalpmmp\pureentities\task\AutoSpawnTask->spawnHostileMob(object pocketmine\level\format\Chunk, object pocketmine\level\Level)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #10 pmsrc/src/pocketmine/scheduler/TaskHandler(137): revivalpmmp\pureentities\task\AutoSpawnTask->onRun(integer 9001)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #11 pmsrc/src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 9001)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #12 pmsrc/src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 9001)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #13 pmsrc/src/pocketmine/Server(2389): pocketmine\plugin\PluginManager->tickSchedulers(integer 9001)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #14 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #15 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #16 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #17 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[8] /server/, string[16] /server/plugins/)
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #18 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
  | 2021-08-05 [20:18:22] [Server thread/CRITICAL]: #19 pmsrc(11): require(string[56] phar:///server/server.phar/src/pocketmine/PocketMine.php)
  | 2021-08-05 [20:18:22] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
  | 2021-08-05 [20:18:22] [Server thread/EMERGENCY]: Please upload the "/server/crashdumps/Thu_Aug_5-20.18.22-WIB_2021.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
  | 2021-08-05 [20:18:22] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/5077003 or use the ID #5077003

</div></div></section></main></div>

**Comment by OguzhanUmutlu** [comment]
which version ? pocketmine?

**Comment by rokibot009** [comment]
Yes i use pmmp
