### ISSUE TITLE
Crash!!

### ISSUE THREAD

**Issue by MadooxMc** [OguzhanUmutlu/ComplexPets#13]
CEST 2021

Error: Tag with name "petOwner" not found and no valid default value given
File: pmsrc/vendor/pocketmine/nbt/src/tag/CompoundTag
Line: 176
Type: RuntimeException

**Comment by OguzhanUmutlu** [comment]
how???????????? its third same issue send phar please its works perfect on me

**Comment by MadooxMc** [comment]
Is think it’s error of me !! 😁
