### ISSUE TITLE
Mw support

### ISSUE THREAD

**Issue by JohnnyX071** [OguzhanUmutlu/ComplexPets#21]
Hello, can you make the pets follow you when you change a world because now they just stay in the world you spawned them!

**Comment by OguzhanUmutlu** [comment]
uh, actually its a feature that i added

**Comment by OguzhanUmutlu** [comment]
like when you change your world actions stop for pets

**Comment by OguzhanUmutlu** [comment]
to make it vanilla-like

**Comment by OguzhanUmutlu** [comment]
i will add an option to config soon.
