### ISSUE TITLE
server crash XD

### ISSUE THREAD

**Issue by usser1976** [OguzhanUmutlu/ComplexPets#3]
Error: Access level to OguzhanUmutlu\ComplexPets\entities\PetEntity::onRiderMount() must be public (as in class pocketmine\entity\Entity)
File: plugins/ComplexPets_dev-11.phar/src/OguzhanUmutlu/ComplexPets/entities/PetEntity
Line: 130
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: ComplexPets v1.0.0

**Comment by OguzhanUmutlu** [comment]
> Error: Access level to OguzhanUmutlu\ComplexPets\entities\PetEntity::onRiderMount() must be public (as in class pocketmine\entity\Entity)
> File: plugins/ComplexPets_dev-11.phar/src/OguzhanUmutlu/ComplexPets/entities/PetEntity
> Line: 130
> Type: E_COMPILE_ERROR
> 
> THIS CRASH WAS CAUSED BY A PLUGIN
> BAD PLUGIN: ComplexPets v1.0.0

use last phar :/
