### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by HybridCybernetic** [OguzhanUmutlu/ComplexPets#6]
Hey, I have an idea for the pet plugin.  My idea would be that you could buy pets with money

**Comment by llPushkarSinghll** [comment]
👍

**Comment by MrBlasyMSK** [comment]
@OguzhanUmutlu

**Comment by OguzhanUmutlu** [comment]
> @OguzhanUmutlu

wat

**Comment by OguzhanUmutlu** [comment]
no u

**Comment by OguzhanUmutlu** [comment]
i will not make shop use other plugins to make shops, because they can
