### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by EvilDevil1175** [OguzhanUmutlu/ComplexPets#8]
everyone can use / pets, and add permissions for pets, Example
wolfpet.permission And that all other pets have permissions

**Comment by MCPEAbdu77** [comment]
Adding to this, I'd like to suggest to implement a limitation to the number of pets a user can have.

**Comment by OguzhanUmutlu** [comment]
> everyone can use / pets, and add permissions for pets, Example
> wolfpet.permission And that all other pets have permissions

i already have that.
